### ISSUE TITLE
Undefined Variable

### ISSUE THREAD

**Issue by joergotttus** [righter83/checkmk-synology-activebackup#2]
PHP Warning:  Undefined variable $out in /volume1/check_ab.php on line 61

Had to remove the trailing "." from $out to remove the error when running the check.
Not sure if this makes the whole thing work correctly.

**Comment by righter83** [comment]
I have declared the $out variable at the beginning, there should be no warning anymore

**Comment by joergotttus** [comment]
Works like a charm - thanks a million, made my day. ;-)
