### ISSUE TITLE
Filter unscheduled Jobs

### ISSUE THREAD

**Issue by joergotttus** [righter83/checkmk-synology-activebackup#3]
Ok, here's another one, maybe more a feature request than an issue:
I have a bunch of jobs that are not scheduled and last run time is months ago. In fact, these were Client-jobs to have the last state of all clients right before they got re-installed.

So my question is: Is it possible to filter out all jobs with no schedule and/or all jobs with a certain jobname?
Thanks.

**Comment by righter83** [comment]
Sure thats possible.

Try 1.3

**Comment by joergotttus** [comment]
Once again, perfect! Thank you for the ultimate fast response times! 👍
